travis:
  secure:
    BINSTAR_TOKEN: Jfs9PmBGMdi2lklmzPhvS5OvyLcyAVPnNN/GPjkLuVyZdyT9Szv5aub1Fz3s89BritOaxgujb1EwRXFM8IJGO8OaW4cfryi64Eli1vOhcJ+pbwC5wmv7KxSSwFtQ45WD/MZrpJH7YoLjSk/NrYdk6KvQ8FNYHv0wftwl/iK9V8RNWZnAv21nouSWXKNJAShETaPSbAUh/mxyx++Py7x0t8MFW0xtDSGgT6VxwO1e2Su0HiS9LII+2f2uWQEWcT86wg8eZ7zqUWRgNmaO9C89iu7So86P/WTeGtY3LuTd5zCW/7U0Ybo2UkFlYKlXfLkSg7H1d64WtQ61qIIGdi3h0/6KPlzgA+aIYI96fkL/J+BT4433iKpLETVjJeST68ACxmJ3qF4xaMyy8HrmYzvtTQtL+VWob6w/vo3qaX1jHXefi9XzPQBnmYsIfKVAJvT8HyfRe/tsKli0XgTMWYKISR4BMgcGIoVYuwbfU6QE0P02GM7v4NjnkOaWLdvU9Gbv8/tbZzN3LZyOhnkb7fk/h6mnEeUUJgjO0Ndr2X6+ve1PwClbhFeyBpHp6DcUADG5agRj0alW2eWLcT7o3hJ/Q7+IdNxdAJHh0Z6jmSGjdP/QOVMTuA7d/Gyq8ItpsCad+g4GdQyzBY60gtYV5V6t/g6XgkpCP8TR4p1G5FSYvlE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
