travis:
  secure:
    BINSTAR_TOKEN: L11Z7UsSW72MhaiTtMweTY3roah8FB9aIDTlTbDrt+GmoQaFq7MyFbL0fsxmVf0xf1JeplgYr0/sZMCoFU2RnD3TnQQ4uHQKT6yhYiCI2CJILrZ6JKnZmBvWL/EeUzc+35/r0MPEe0f7AZO9YKcuGE0IRR5P8zAEgvCZF/+KQodYwZuRF0nQIRxORQ5PITYUUBJ0/7BjFf0XO28E32tlRET7yagHX/DBMP151J7P5K0+jnpBSNXJIY4PNBAzmpQ9NirV7XFP/6fYCyGde6ZsbDEku1LfNidoMyFmuXcjZWpoo2l0ZlNp4hr2LXnWJdnJl9U7QvEMQS285gvPfWwSSvxckbCoKlk+NrsABpUpDQbjN1WK2OM2ymnQ4NGZk19BpnYjlsgR2nvNdvTKFiliuZd21SDn2Z30VGjrda2YGAlktkvHq+WMjU4GsJifQd2ceFH34KWR7rDp0yPKYlJfpJXACvciKHLkB75nC0kp75Y8ZvLennyY4KTKW1rVs4yAkc8BGyaaBAd3KKZhO1n7A3aId4oBPvb037Kv00FfhG65n/xQ5ZYAFYRqo2TPE/3twcFwQ1Z5eRchvD8Rt+U1+GGfRu04BW050d3x/VspeBqQQv7n04gfNAmNqk/IbQAcyUQV9X5sUrc0718Moj2srl0AP5TGJyUI8CVCbDN9LRM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
